version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: bert6
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
