apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: your-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: your-app
  minReplicas: 2  # Minimum pod sayısı
  maxReplicas: 10  # Maksimum pod sayısı
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50  # %50 CPU kullanımına ulaşıldığında ölçekleme yap
